language: bash
sudo: false
install:
  - sudo apt-get install libpcre3 libpcre3-dev libevent-dev
  - cd /tmp && git clone https://github.com/lloyd/yajl.git && cd yajl
  - source ./configure && make && sudo make install
  - cd /tmp && git clone https://github.com/KennethanCeyer/io.git && cd io
  - sudo bash ./build.sh
script:
  - io --version
  - bash ./run_tests.sh