language: bash
sudo: required
install:
  - sudo apt-get install libpcre3 libpcre3-dev libevent-dev
  - cd /tmp && git clone https://github.com/lloyd/yajl.git --quiet && cd yajl
  - bash ./configure && make && sudo make install
  - cd /tmp && git clone https://github.com/IoLanguage/io.git --quiet io && cd io
  - mkdir build && cd build && cmake ..
script:
  - io --version
  - bash ./run_tests.sh